version: "3.8"
services:
  fastapi_db:
    image: postgres:15-alpine
    build:
      context: .
    container_name: postgres_db
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

